### ISSUE TITLE
filenames don't match?

### ISSUE THREAD

**Issue by EthanJUCB** [tribell4310/reliosparc#1]
Hi, I tried to convert the coordination of particles picked in cryoscparc to the individual coordination star files for relion using this script. 

Here is the error I had.

Detected a Raw_data folder in this directory.
Reading the cryosparc file...
Parsing micrograph names from star file...
Matching micrograph names between cs and star files...
Traceback (most recent call last):
  File "cs_to_stars.py", line 266, in <module>
    main(sys.argv[1], sys.argv[2])
  File "cs_to_stars.py", line 72, in main
    print("\nERROR: There was no match found for the following micrograph: "+target)
UnboundLocalError: local variable 'target' referenced before assignment

The micrographs have identical names. I wonder if the parent folder name matters, since it is different in cryosparc from that in realign.

For example, the name of a micrograph in the cs file is J1/Imported/AAA.mrc, while the name in micrograph_ctf.star is Micrographs/AAA.mrc. 

I tried to use the same folder name but still got the same error. I wonder if you have any suggestions. Many thanks.

**Comment by tribell4310** [comment]
Thanks for raising this issue - the script was detecting micrograph names in star files by assuming that they had already been through motion correction, which wasn't compatible with the "Micrographs/AAA.mrc" names in your star file.  I've updated the script to parse star files more permissively.

Please give it a shot with the updated version and let me know if the problem lingers.

**Comment by EthanJUCB** [comment]
It works. That is super cool. Thanks very much.

**Comment by tribell4310** [comment]
Glad it's working - happy processing!

**Comment by ghost** [comment]
Hi tribell4310,

I believe I may be having a similar issue to EthanJUCB. I have picked particles in cryosparc and want to export the coordinates to Relion to do extraction and 2D classification. When I execute the code it seems to run fine (no errors), except that the output is not multiple star files (one per micrograph) but a single large file with all the coordinates but no information about which micrograph they came from.

The command I'm running is:

`$ python3 reliosparc-main/cs_to_stars.py P1/J28/picked_particles.cs CtfFind/job012/micrographs_ctf.star`

I suspect the issue is in the naming of the files. The micrographs_ctf.star file produced by CTFFIND in Relion name my micrographs with the format 0001_Nov28_16_05_04.mrc, but in Cryosparc the same micrograph would be named J6/motioncorrected/008536756295951695202_Nov28_16.05.04_patch_aligned_doseweighted.mrc (Relion changed the periods in the filename to underscores, but cryosparc did not). Could this be causing the problem? I would be grateful if you had any advice!

**Comment by tribell4310** [comment]
Hi stepheem, thanks for raising this issue.  Our core facility doesn't use "." in filenames, so I never would have caught this testing on our data.  I've modified the code to convert "." to "_" in the cryosparc names during matching.  Please give the updated version a try and let me know if the problem lingers.

**Comment by ghost** [comment]
Thanks for looking into it - I had a go with the updated script but unfortunately it exited with an error:

Reading the cryosparc file...
Parsing micrograph names from star file...
Matching micrograph names between cs and star files...
Traceback (most recent call last):
  File "reliosparc-main/cs_to_stars.py", line 294, in <module>
    main(sys.argv[1], sys.argv[2])
  File "reliosparc-main/cs_to_stars.py", line 59, in main
    if no_ext(previous_soln) in str(no_dot(f[i][start_index])):
  File "reliosparc-main/cs_to_stars.py", line 242, in no_dot
    return inStr.replace(".", "_")
TypeError: a bytes-like object is required, not 'str'

**Comment by tribell4310** [comment]
Whoops, clumsy me - sorry about that.  I've updated the code, and it shouldn't throw this error again.

If this version doesn't correct the issue, would you please post your micrographs_ctf.star and your .cs file so I can replicate the problem from my end?

**Comment by bonillst** [comment]
Hello, I am having the same problem described above: only one file is generated  (_autopick.star) instead of one file for each micrograph. I am attaching the .cs file and the micrographs_ctf.star. I have tried with different cryoSPARC jobs (e.g. extract particles, inspect particles, etc.) but the results are the same. Thanks so much for your help!
[micrographs_ctf.star.zip](https://github.com/tribell4310/reliosparc/files/7117038/micrographs_ctf.star.zip)
[extracted_particles.cs.zip](https://github.com/tribell4310/reliosparc/files/7117101/extracted_particles.cs.zip)
[_autopick.star.zip](https://github.com/tribell4310/reliosparc/files/7117103/_autopick.star.zip)

**Comment by tribell4310** [comment]
Thank you for posting this, I'll take a look.

**Comment by bonillst** [comment]
@tribell4310 , I think that the problem was that the number of micrographs in the cryosparc and relion folders are different (some of the micrographs were filtered out using the 'manually curate exposures' job in cryoSPARC); I repeated the particle pick in cryoSPARC using all of the micrographs, so now the number of micrographs are the same in both programs; however now I am running into a different problem; I am getting this error:  
File "cs_to_stars.py", line 294, in <module>
    main(sys.argv[1], sys.argv[2])
  File "cs_to_stars.py", line 120, in main
    g = open("Raw_data/"+no_ext(item)+"_autopick.star", "w", newline="")
TypeError: 'newline' is an invalid keyword argument for this function

**Comment by tribell4310** [comment]
Hi bonillst, the inconsistent micrographs issue makes sense.  For the second error you posted, can you confirm that you're running the script with python 3?  The "newline" argument for the built-in open() function has been standard since python 3, but breaks for me when running in a python2.7 environment.  You can check the version using:

python --version

**Comment by bonillst** [comment]
hi @tribell4310 , actually the first problem persists even with the same number of micrographs in both relion and cryoSPARC; the second problem was simply because I was using the wrong version of python.  But, yes, I am still getting only one file instead of one file for each micrograph :/

**Comment by tribell4310** [comment]
Ah, unfortunate.  Would you please post your updated cs and star files?  I can take a look tomorrow morning.

Thank you for taking the time to post and comment.  Posts like this identify edge cases that show how the script can be made more robust.

**Comment by bonillst** [comment]
Thanks so much for your help @tribell4310 ; the updated cryoSPARC and reliosparc files are:
[extracted_particles.cs.zip](https://github.com/tribell4310/reliosparc/files/7119178/extracted_particles.cs.zip)
[_autopick.star.zip](https://github.com/tribell4310/reliosparc/files/7119179/_autopick.star.zip)

the micrographs_ctf.star file is the same as in the previous post

**Comment by tribell4310** [comment]
Hi @bonillst , I've found the bug and updated the cs_to_stars script.  It's now producing the correct files from my end.  Please let me know if any other issues arise.

**Comment by bonillst** [comment]
Thanks so much @tribell4310 !! Seems to be working! I'll let you know if I run into any other problems.  Thanks for fixing the bug and updating the code so quickly!

**Comment by tribell4310** [comment]
Great!  Happy processing!

**Comment by Tiannamega** [comment]
Hi tribell4310, I have a problem when using the cs_to_stars.py code.  Here is the error I had.

Detected a Raw_data folder in this directory.
Reading the cryosparc file...
Parsing micrograph names from star file...
Matching micrograph names between cs and star files...
Traceback (most recent call last):
  File "cs_to_stars.py", line 291, in <module>
    main(sys.argv[1], sys.argv[2])
  File "cs_to_stars.py", line 46, in main
    start_index = infer_index(f)
  File "cs_to_stars.py", line 216, in infer_index
    return startInd
UnboundLocalError: local variable 'startInd' referenced before assignment

I have no idea, looking forward to your reply.

**Comment by tribell4310** [comment]
Hi Tiannamega, thanks for sending this along.  Cryosparc recently restructured many of their internal data formats in the transition from cs3 to cs4, which is likely causing this problem.

If you're willing to, would you please share: (a) the version of cryosparc you used to generate your .cs file, (b) your .cs file that gave the error, and (c) your relion .star file?  I'd be happy to take a look, and probably create a separate version of this script for cs4.

Cheers, Tristan

**Comment by Tiannamega** [comment]
Glad to receive your reply，Tristan.
I am using the v4.0.0 of CryoSPARC. I would like to share the .cs file and relion .star file.  
[J58_passthrough_particles.zip](https://github.com/tribell4310/reliosparc/files/10409103/J58_passthrough_particles.zip)
[micrographs_ctf.zip](https://github.com/tribell4310/reliosparc/files/10409104/micrographs_ctf.zip)
Hope it goes smoothly.

**Comment by tribell4310** [comment]
Sorry this took so long to get to - work has been a bit crazy.

It looks like this .cs file doesn't contain the particle coordinates.  In the update to cs4, the developer team changed what data is encoded in what .cs files.  Please try a different .cs file.  So far, I've only validated that the "extracted_particles.cs" files from extraction jobs contain particle data.
