### ISSUE TITLE
swapxy and inverty options are likely needed for your program

### ISSUE THREAD

**Issue by donghuachensu** [tribell4310/reliosparc#4]
Hi, I tried your program to convert cryosparc particle coordinates back to Relion for re-extraction, then run Class2D in Relion and unfortunately the results from Class2D were junk. After I read this thread in cryosparc forum (https://discuss.cryosparc.com/t/bayesian-polishing-of-cryosparc-processed-particles/3241), I guess some options (e.g., swapxy and inverty from csparc2star.py (https://github.com/asarnow/pyem)) are likely needed for your program to be successful. Thanks!

**Comment by tribell4310** [comment]
Thanks for raising this issue.  A lot has changed in the cryosparc and relion ecosystems since this script was first developed.  I'm happy to take a look at the issue.

Just out of curiosity, did you collect your data using EPU, SerialEM, or something else?  This could be the classic ill-defined handedness problem creeping in.

To address the issue, I'll need some more details.  Specifically, would you please share screenshots of a micrograph with 5-10 particle picks in cryosparc and what you see for the particle picks in relion after running this script?  In addition, could you let me know what versions of cryosparc and relion you're using?

**Comment by donghuachensu** [comment]
Sorry for my late reply. I used SerialEM to collect my data. Relion version is 3.1.2 and cryoSPARC version is v3.3.2+220824. Unfortunately I don't have the screenshots for Relion-picked and cryoSPARC-picked particles shown in a micrograph.

**Comment by tribell4310** [comment]
flipx and flipy options have been added in the latest release.
